#!/usr/bin/env bash
# shellcheck shell=bash
# WP-SCP-024 slice 024B scaffolder contract (D-044).
#
# Generates the adopter-side wrapper, CODEOWNERS snippet, PR body
# template, and manifest from the canonical adopter-wrapper template.
# Bootstrap-only: refuses to run in CI or GitHub Actions.
#
# Reference: docs/DECISIONS.md D-044; docs/plans/WP-SCP-024-estate-cascade.md
# §5.3; docs/adoption/ADOPT-001-project-onboarding.md §12.

set -euo pipefail

SCP_REPO_ROOT="${SCP_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
TEMPLATE_PATH="${SCP_REPO_ROOT}/templates/adopter-wrapper.yml.tmpl"
RECOMMENDED_SCP_SHA="f6c4ce6dcbfb484d4202575d1d513dd376cfb5a5"   # post-TF-PIM-001-cleanup main HEAD 2026-05-24; canonical recommended pin for new adopters generated by this scaffolder. Replaces the historical V1_0_0_SCP_SHA constant (which pinned v1.0.0 = 04523fac and pre-dated WP-SCP-023 023B's scorecard-emit input + Wave D'.1's scp-sha + selftest-mode inputs; v1.0.0 default is now scaffolder-broken because the generated wrapper has inputs the v1.0.0 policy-check.yml doesn't declare). TF-023E-002 attest-scorecard permissions-ceiling concern is now MOOT — Wave D'.1 axis F closure added `attestations: write + id-token: write` at caller-job level in the scaffolder template, satisfying the ceiling. Closes FUP-WP-SCP-024-SCAFFOLDER-V1.2-INCOMPAT-001 + FUP-SCP-V1-0-0-SHA-NAMING-001.
V1_0_0_SCP_SHA="$RECOMMENDED_SCP_SHA"   # back-compat alias for any caller of this script that references the historical name; deprecation removal targeted for cohort cascade 024D+ ship.

usage() {
  cat >&2 <<'EOF'
Usage: scaffold-downstream.sh --adopter-repo OWNER/NAME --default-branch <main|master|develop> --scp-sha <40-char-sha> --scorecard-emit <true|false> --output-dir <local-clone-path>

Required:
  --adopter-repo OWNER/NAME      Target adopter repository.
  --default-branch <branch>      Adopter default branch (main, master, develop).
  --scp-sha <40-char-sha>        SCP wrapper pin SHA.
  --scorecard-emit <true|false>  Wrapper scorecard emit toggle.
  --output-dir <path>            Existing writable output directory.

Flags:
  --help / -h                    Show this help.
EOF
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

warn() {
  printf 'WARNING: %s\n' "$*" >&2
}

sha256_file() {
  python3 -c 'import hashlib, pathlib, sys
path = pathlib.Path(sys.argv[1])
print(hashlib.sha256(path.read_bytes()).hexdigest())' "$1"
}

if [ "${CI:-}" = "true" ] || [ "${GITHUB_ACTIONS:-}" = "true" ]; then
  die "bootstrap-only: refuse to run in CI=true or GITHUB_ACTIONS=true"
fi

if [ ! -f "$TEMPLATE_PATH" ]; then
  die "missing template: $TEMPLATE_PATH"
fi

ADOPTER_REPO=""
DEFAULT_BRANCH=""
SCP_SHA=""
SCORECARD_EMIT=""
OUTPUT_DIR=""

while [ $# -gt 0 ]; do
  case "$1" in
    --adopter-repo)
      [ $# -ge 2 ] || die "--adopter-repo requires a value"
      ADOPTER_REPO="$2"
      shift 2
      ;;
    --default-branch)
      [ $# -ge 2 ] || die "--default-branch requires a value"
      DEFAULT_BRANCH="$2"
      shift 2
      ;;
    --scp-sha)
      [ $# -ge 2 ] || die "--scp-sha requires a value"
      SCP_SHA="$2"
      shift 2
      ;;
    --scorecard-emit)
      [ $# -ge 2 ] || die "--scorecard-emit requires a value"
      SCORECARD_EMIT="$2"
      shift 2
      ;;
    --output-dir)
      [ $# -ge 2 ] || die "--output-dir requires a value"
      OUTPUT_DIR="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown flag: $1"
      ;;
  esac
done

[ -n "$ADOPTER_REPO" ] || die "--adopter-repo is required"
[ -n "$DEFAULT_BRANCH" ] || die "--default-branch is required"
[ -n "$SCP_SHA" ] || die "--scp-sha is required"
[ -n "$SCORECARD_EMIT" ] || die "--scorecard-emit is required"
[ -n "$OUTPUT_DIR" ] || die "--output-dir is required"

if ! printf '%s' "$ADOPTER_REPO" | grep -qE '^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$'; then
  die "--adopter-repo '$ADOPTER_REPO' must match owner/name"
fi

case "$DEFAULT_BRANCH" in
  main|master|develop) ;;
  *)
    die "--default-branch '$DEFAULT_BRANCH' must be one of main, master, develop"
    ;;
esac

if ! printf '%s' "$SCP_SHA" | grep -qE '^[a-f0-9]{40}$'; then
  die "--scp-sha '$SCP_SHA' must be exactly 40 lowercase hex characters"
fi

case "$SCORECARD_EMIT" in
  true|false) ;;
  *)
    die "--scorecard-emit '$SCORECARD_EMIT' must be true or false"
    ;;
esac

case "$OUTPUT_DIR" in
  ..|../*|*/../*|*/..)
    die "--output-dir '$OUTPUT_DIR' must not contain path-traversal segments"
    ;;
esac

OUTPUT_DIR="$(
  readlink -f "$OUTPUT_DIR" 2>/dev/null ||
  python3 -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' "$OUTPUT_DIR"
)"

if [ ! -d "$OUTPUT_DIR" ] || [ ! -w "$OUTPUT_DIR" ]; then
  die "--output-dir '$OUTPUT_DIR' must exist and be writable"
fi

case "$OUTPUT_DIR" in
  /etc|/etc/*|/private/etc|/private/etc/*|/var|/var/*|/private/var|/private/var/*|/usr|/usr/*|/private/usr|/private/usr/*|/sys|/sys/*|/private/sys|/private/sys/*|/proc|/proc/*|/private/proc|/private/proc/*|/tmp|/tmp/*|/private/tmp|/private/tmp/*)
    die "--output-dir '$OUTPUT_DIR' refuses system path parents (/etc, /var, /tmp, /usr, /sys, /proc, plus macOS /private equivalents)"
    ;;
esac

if ! git -C "$SCP_REPO_ROOT" cat-file -e "${SCP_SHA}^{commit}" 2>/dev/null; then
  printf 'ERROR: --scp-sha %s does not exist in SCP repo\n' "$SCP_SHA" >&2
  exit 2
fi

# TF-023E-002 attest-scorecard permissions-ceiling warning REMOVED 2026-05-24
# (FUP-WP-SCP-024-SCAFFOLDER-V1.2-INCOMPAT-001 closure): obsolete because
# Wave D'.1 axis F closure added `attestations: write + id-token: write` at
# caller-job level in the scaffolder template (templates/adopter-wrapper.yml.tmpl).
# The called workflow's attest-scorecard job permissions ceiling is now
# satisfied by every scaffolder-generated wrapper, regardless of scp-sha pin.
#
# Pre-Wave-D'.1 SHA warning (NEW 2026-05-24): a `--scp-sha` value that pre-
# dates Wave D'.1 lacks the `scp-sha` required input + `selftest-mode` input
# that the post-Wave-D'.1 scaffolder template tries to pass via the `with:`
# block. This causes GitHub Actions to reject the wrapper at parse time
# (phantom-input failure mode that originally drove FUP-WP-SCP-024-SCAFFOLDER-
# V1.2-INCOMPAT-001 in the inverse direction). Warn the operator.
if [ "$SCP_SHA" != "$RECOMMENDED_SCP_SHA" ]; then
  WAVE_D_PRIME_1_SHA="6653cf9b66de23f521c45fe681f9f787b943312a"
  if git -C "$SCP_REPO_ROOT" cat-file -e "${WAVE_D_PRIME_1_SHA}^{commit}" 2>/dev/null && \
     ! git -C "$SCP_REPO_ROOT" merge-base --is-ancestor "$WAVE_D_PRIME_1_SHA" "$SCP_SHA" 2>/dev/null; then
    warn "--scp-sha $SCP_SHA pre-dates Wave D'.1 ($WAVE_D_PRIME_1_SHA, 2026-05-23). The scaffolder template's \`with:\` block declares inputs (scp-sha, selftest-mode) that pre-Wave-D'.1 policy-check.yml does NOT accept. Generated wrapper will FAIL at GitHub Actions parse time (phantom-input rejection). RECOMMENDED: use --scp-sha $RECOMMENDED_SCP_SHA or any SHA from main post-2026-05-23. Continuing emission per operator request."
  fi
fi

MAIN_HEAD_SHA="$(git -C "$SCP_REPO_ROOT" rev-parse main 2>/dev/null || true)"
if [ -z "$MAIN_HEAD_SHA" ]; then
  warn "could not resolve SCP main HEAD; continuing without HEAD-lineage warning"
elif [ "$SCP_SHA" != "$MAIN_HEAD_SHA" ]; then
  warn "--scp-sha $SCP_SHA is not current SCP main HEAD $MAIN_HEAD_SHA; emitted wrapper will be behind main"
fi

WORKFLOWS_DIR="${OUTPUT_DIR}/.github/workflows"
mkdir -p "$WORKFLOWS_DIR"

wrapper_path="${WORKFLOWS_DIR}/policy-check-wrapper.yml"
codeowners_snippet_path="${OUTPUT_DIR}/.github/CODEOWNERS-snippet.txt"
pr_body_path="${OUTPUT_DIR}/CASCADE-PR-BODY.md"
manifest_path="${OUTPUT_DIR}/MANIFEST.json"

sed \
  -e "s/{{DEFAULT_BRANCH}}/${DEFAULT_BRANCH}/g" \
  -e "s/{{SCP_SHA}}/${SCP_SHA}/g" \
  -e "s/{{SCORECARD_EMIT}}/${SCORECARD_EMIT}/g" \
  "$TEMPLATE_PATH" >"$wrapper_path"

if grep -Eq '{{[A-Za-z0-9_]+}}' "$wrapper_path"; then
  die "template substitution incomplete: unreplaced markers remain in emitted wrapper"
fi

cat >"$codeowners_snippet_path" <<'EOF'
# CODEOWNERS snippet for policy-check-wrapper.yml — adopter merges this line into existing CODEOWNERS, replacing <adopter-CODEOWNERS-account> with the right account/team.
.github/workflows/policy-check-wrapper.yml @<adopter-CODEOWNERS-account>
EOF

cat >"$pr_body_path" <<'EOF'
<!-- adopter: review/edit -->
This PR adds the SCP wrapper and required-check bootstrap for the adopter repo. Estimated cost impact is intentionally small: T-024-09 expects roughly 2-5 minutes on ubuntu-24.04, under 10% of a typical adopter CI bill.

<!-- adopter: review/edit -->
Bus-factor-1 is disclosed explicitly here: invariant 9 and D-031 both acknowledge the single-operator posture, and the 2026-07-21 quarterly review is the named follow-up for that exposure.

<!-- adopter: review/edit -->
## What this PR does NOT touch

This cascade slice is purely additive — it adds `.github/workflows/policy-check-wrapper.yml` and, if needed, a `.github/CODEOWNERS-snippet.txt` line for that file. It does NOT modify your existing CI workflows, your build config (`package.json` / `pyproject.toml` / equivalent), your README, your service config, branch-protection rules from this PR, or any other pre-existing file. Per WP-SCP-024 plan-doc §2 invariant 3, the cascade does not touch existing adopter content.

<!-- adopter: review/edit -->
Invariant 1 consent surface is explicit here: the adopter owner chooses the wrapper SHA pin and this PR is the audit record for that choice, not an automatic transitive update.

<!-- adopter: review/edit -->
Version-skew tolerance remains the design point: T-024-04 and the D-036 deprecation ramp are what make SHA pin bumps safe enough to operate across adopter cadence differences.

<!-- adopter: review/edit -->
Scorecard emit stays opt-in by default: TF-023E-002 defers the wrapper-shape change unless the adopter is public or org-owned per TF-023E-001.
EOF

emitted_at="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
wrapper_sha="$(sha256_file "$wrapper_path")"
codeowners_sha="$(sha256_file "$codeowners_snippet_path")"
pr_body_sha="$(sha256_file "$pr_body_path")"

python3 - "$emitted_at" "$ADOPTER_REPO" "$DEFAULT_BRANCH" "$SCP_SHA" "$SCORECARD_EMIT" "$manifest_path" \
  ".github/workflows/policy-check-wrapper.yml" "$wrapper_sha" \
  ".github/CODEOWNERS-snippet.txt" "$codeowners_sha" \
  "CASCADE-PR-BODY.md" "$pr_body_sha" <<'PY'
import json
import sys

emitted_at, adopter_repo, default_branch, scp_sha, scorecard_emit, manifest_path = sys.argv[1:7]
rest = sys.argv[7:]
files = []
for path, sha in zip(rest[0::2], rest[1::2]):
    files.append({"path": path, "sha256": sha})

payload = {
    "emitted_at": emitted_at,
    "adopter_repo": adopter_repo,
    "default_branch": default_branch,
    "scp_sha": scp_sha,
    "scorecard_emit": scorecard_emit == "true",
    "files": files,
}
with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(payload, f, indent=2)
    f.write("\n")
PY

_verify_emitted_wrapper_repo_exists() {
  # Closes FUP-WP-SCP-024-SCAFFOLDER-EMIT-PREFLIGHT-001 (BACKLOG.md Phase 12).
  # Driver: FUP-WP-SCP-024-SCAFFOLDER-RENAME-SWEEP-001 (trailing-dash regression
  # in PR #152 wrapper template caused mapp-doc-agent + Recommender wrappers to
  # land referencing `jrnb2024/standards-control-plane-` (404). Bug was caught
  # post-merge by GHA startup_failure, not pre-commit. This post-emit verify
  # would have caught it pre-commit.
  #
  # Greps the emitted wrapper for the `uses:` line, extracts owner/name, and
  # calls `gh api repos/<owner>/<name>` asserting 200. Soft-skip if `gh` is
  # not installed or not authenticated (bootstrap-only script; we don't want
  # to add a hard dependency on gh for the scaffolder, but if it's available
  # we use it).
  local wrapper="$1"
  local uses_line owner_name http_status
  uses_line="$(grep -E '^\s*uses:\s*\S+/\.github/workflows/' "$wrapper" || true)"
  if [ -z "$uses_line" ]; then
    warn "post-emit verify: no \`uses:\` clause found in $wrapper; skipping repo-exists check"
    return 0
  fi
  # uses: <owner>/<name>/.github/workflows/<file>@<sha>
  owner_name="$(printf '%s' "$uses_line" | sed -E 's|^\s*uses:\s*([^/]+/[^/]+)/.*|\1|')"
  if [ -z "$owner_name" ] || ! printf '%s' "$owner_name" | grep -Eq '^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$'; then
    warn "post-emit verify: could not extract owner/name from \`uses:\` line; skipping repo-exists check (line=$uses_line)"
    return 0
  fi
  if ! command -v gh >/dev/null 2>&1; then
    warn "post-emit verify: gh CLI not installed; skipping repo-exists check for $owner_name (install gh + re-run to enable this safety net)"
    return 0
  fi
  if ! gh auth status >/dev/null 2>&1; then
    warn "post-emit verify: gh not authenticated; skipping repo-exists check for $owner_name (run \`gh auth login\` + re-run to enable this safety net)"
    return 0
  fi
  http_status="$(gh api -i "repos/${owner_name}" 2>/dev/null | head -1 | awk '{print $2}' || true)"
  if [ "$http_status" = "200" ]; then
    printf 'OK: post-emit verify — wrapper `uses:` references %s (HTTP 200)\n' "$owner_name" >&2
    return 0
  fi
  # gh api returns non-zero on 4xx; the http_status variable may be empty.
  # Re-run with --silent and check exit code as defense in depth.
  if gh api "repos/${owner_name}" >/dev/null 2>&1; then
    printf 'OK: post-emit verify — wrapper `uses:` references %s (gh api OK)\n' "$owner_name" >&2
    return 0
  fi
  die "post-emit verify FAILED: wrapper at $wrapper references repo $owner_name which gh api cannot resolve (likely 404). Re-check the scaffolder template + SCP repo rename history; this is the FUP-WP-SCP-024-SCAFFOLDER-RENAME-SWEEP-001 trailing-dash class of bug."
}

_verify_emitted_wrapper_repo_exists "$wrapper_path"

printf 'OK: emitted 4 files under %s; manifest at %s\n' "$OUTPUT_DIR" "$manifest_path" >&2
